### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RiotGamesPlayer** [Meviii/LOL-Account-Checker#29]
It is recommended to set the maximum number of accounts. When I put in 300 accounts, it almost occupies 100% of  RAM, and the computer becomes very sluggish.Or carry out hierarchical distribution processing

**Comment by RiotGamesPlayer** [comment]
And it will still report an error, although it does not tell me where the error occurred

**Comment by Meviii** [comment]
Hey, thanks for letting me know about that. Do you use multiple threads while checking those accounts? If so, how many? I am wondering if it's a problem where you are checking accounts with minimal threads, and overtime, the RAM usage increases (although it shouldn't).

**Comment by Meviii** [comment]
I double checked the RAM usages and everything seems normal. Using a lot of threads can cause RAM issues. Also, I've fixed errors that would cause the program to crash while checking.

**Comment by RiotGamesPlayer** [comment]
When i finish running the software，there is nothing outputed.![image](https://user-images.githubusercontent.com/126843138/225991480-54abd05b-662a-4452-8074-e7c8587574ed.png)

**Comment by RiotGamesPlayer** [comment]
About 27 threats，and click refresh，there is nothing happened

**Comment by Meviii** [comment]
Okay, 27 threads might be a little too much for now. I recommend using at most 4 threads since I haven't really tested the program with many threads.

I'll look into it and try to find the reason to why it isn't working regardless.
