### ISSUE TITLE
Re adding to queue 24/7

### ISSUE THREAD

**Issue by Dorlander** [Meviii/LOL-Account-Checker#35]
Remaining Combos: 13
Starting task for mecairos
Initializing new Connection. Port: 50028, Auth Token: 8Wsf9AMo8NmP3Ts47xIdtI
Sending POST request. URL: rso-auth/v2/authorizations
Aggregate Exception at Authorization. Re adding to queue

**Comment by Meviii** [comment]
Thanks for letting me know, will look into it. How many threads were you running at the time?

**Comment by Dorlander** [comment]
Nvm 1 or 8, same problem -------- Исходное сообщение --------Тема: Re: [Meviii/LOL-Account-Checker] Re adding to queue 24/7 (Issue #35)От: Meviii Кому: Meviii/LOL-Account-Checker Копия: Dorlander ,Author 
Thanks for letting me know, will look into it. How many threads were you running at the time?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Meviii/LOL-Account-Checker/issues/35#issuecomment-1481818683",
"url": "https://github.com/Meviii/LOL-Account-Checker/issues/35#issuecomment-1481818683",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Meviii** [comment]
Oh okay, just another question. Are you using the latest release(1.3)?

**Comment by Dorlander** [comment]
> Oh okay, just another question. Are you using the latest release(1.3)?

any release

**Comment by Meviii** [comment]
Ok, will look at it. Thanks for letting me know.

**Comment by erenguldal** [comment]
@Meviii 
Can you give me your Discord account, I want to ask something.

**Comment by Meviii** [comment]
@erenguldal 
> @Meviii Can you give me your Discord account, I want to ask something.

Mevi#0001

@Dorlander 
> > Oh okay, just another question. Are you using the latest release(1.3)?
> 
> any release

Restarting the application seems to solve the problem. Please let me know if you still face the problem.

**Comment by Dorlander** [comment]
@Meviii yea all fine now, tnx for fix. but can u add use my own proxy for each session?
