### ISSUE TITLE
Cannot see Skin list

### ISSUE THREAD

**Issue by bohos** [Meviii/LOL-Account-Checker#38]
I downloaded your application to view the skins I have in League of Legends. However, it doesn't quite work for me. Could you help me?

**Comment by bohos** [comment]
Logging in with my account has worked so far and the logs look good too. However, the account is not displayed under "Accounts".

**Comment by Meviii** [comment]
> I downloaded your application to view the skins I have in League of Legends. However, it doesn't quite work for me. Could you help me?

I need more information and/or screenshots.



> Logging in with my account has worked so far and the logs look good too. However, the account is not displayed under "Accounts".

That is not normal, can you retry your account separately with a single thread?

**Comment by Meviii** [comment]
Closed due to inactivity.
