### ISSUE TITLE
Bad request when checking accounts

### ISSUE THREAD

**Issue by plonsik** [Meviii/LOL-Account-Checker#39]
Hi,
I can't make it work. Getting bad requests all the time. Manual log in works just fine
BadRequest - 
{"errorCode":"RPC_ERROR","httpStatus":400,"implementationDetails":{},"message":"session_not_found: No previous RSO session found"}

**Comment by Dorlander** [comment]
> No previous RSO session found"}

u must login into any acc without checker

**Comment by plonsik** [comment]
Not changing much :( 
logged in and launched before app - error
logged in and then launched app - error

**Comment by plonsik** [comment]
okay i've got it, cant have saved logins in client
