### ISSUE TITLE
RIOT API error

### ISSUE THREAD

**Issue by MErnie** [Meviii/LOL-Account-Checker#41]
Tasks Completed.
Remaining Combos: 1094
Starting task for facukhoury
Starting task for facukhou
Initializing new Connection. Port: 56942
, Auth Token: vMFFaySvkejeQUMaVGr
Initializing new Connection. Port: 63859, Auth Token: CI83YlPZzl8TaClIm
Sending POST request. URL: rso-auth/v2/authorizations
Response: OK
Sending PUT request. URL: rso-auth/v1/session/credentials
Response: BadRequest
Riot Session error. Try again later.
Sending POST request. URL: rso-auth/v2/authorizations
Response: OK
Sending PUT request. URL: rso-auth/v1/session/credentials
Response: BadRequest
Riot Session error. Try again later.

**Comment by Meviii** [comment]
No fix for this atm. It generally occurs when there are multiple threads in use. If you are using less than 8 threads and it still happens, please let me know.

**Comment by Meviii** [comment]
Will work on a fix for this soon or later.
