### ISSUE TITLE
Auth Token error

### ISSUE THREAD

**Issue by rolliic** [Meviii/LOL-Account-Checker#42]
Tasks Completed.
Remaining Combos: 2500
Starting task for gnmhtpmn
Initializing new Connection. Port: 56972, Auth Token: wAAe85e9e88PifpYBkss97
and then it gaves me an eror of a wrong client path 
i did sit the right path for game and client
and use 8 threads and still gaves the same error

**Comment by rolliic** [comment]
This is the type of combos im using
![image](https://user-images.githubusercontent.com/121501940/229925851-30407639-1dee-4c35-8138-e67e7a28f02e.png)
and it also good an alt acc the i made and few others  banned after using the tool
![image](https://user-images.githubusercontent.com/121501940/229926463-3513ebce-428e-4e72-8c2a-dad5c872a5a8.png)
and here is my sittings
![image](https://user-images.githubusercontent.com/121501940/229926709-6eee95ae-aa44-4ef5-a6b1-9354bba9abe8.png)

**Comment by Meviii** [comment]
Firstly, an account cannot get banned after using this tool. If that was the case, these tools would not exist and be made available to create. The program does not do anything against the TOS of Riot apart from extracting data and performing common tasks such as disenchanting skins and champs.

Secondly, coming to your problem, you configured the path settings incorrectly, the paths should be switched. 

Furthermore, I don't know how your account can get banned if you weren't even able to properly run the program.

If you still believe the tool is what caused the ban, please provide the details on why you were banned by asking Riot. 

P.S. I have tested my own accounts over 150+ times while testing this tool and never did a single one get banned.

**Comment by rolliic** [comment]
How i can switch the path or at least make it work then

**Comment by rolliic** [comment]
![image](https://user-images.githubusercontent.com/121501940/229952061-51d838c4-69d4-49ee-9048-d7493676eddd.png)
i did what you told me but as you see same thing maybe there like any exrta tips like all i did was
downloading the file
extract it on desktop
open the account cheaker LOL-Account-Checker-main\Account Checker Release
and put the combos set the thread count to 8
and that's it

**Comment by rolliic** [comment]
update : this time it didn't gave me an error but it keeps restrating in like that and the account left amount stays between 4990 and 5000
