### ISSUE TITLE
add banned checker and use proxy 

### ISSUE THREAD

**Issue by soydct** [Meviii/LOL-Account-Checker#43]
add banned checker and use proxy

**Comment by soydct** [comment]
and server checker

**Comment by Meviii** [comment]
I can do the banned checker soon however not the proxy anytime soon. Regarding the server checker, what do you mean?

**Comment by soydct** [comment]
like US TW

**Comment by Meviii** [comment]
Could you be more detailed on what you mean by a server checker? Do you mean to check which server is online (if so, the checker will fail if the server isn't online)?

**Comment by Meviii** [comment]
Closed due to inactivity.
