### ISSUE TITLE
results 

### ISSUE THREAD

**Issue by lucifer00123** [Meviii/LOL-Account-Checker#44]
results wont show, so it does check them by using api but when you go to accounts aka checked accounts nothing shows its empty and refresh button is useless i think, i tried 5 of my accounts as well all working btw please fix this and thanks.

**Comment by Meviii** [comment]
How many threads were you using? It doesn't make sense for it to not be saved if the accounts were checked successfully. I'll look into this regardless.

**Comment by lucifer00123** [comment]
3 only

**Comment by ErickDDO** [comment]
I am using 8 and it's perfect, all I have to say is congratulations! Great job!

**Comment by Meviii** [comment]
> I am using 8 and it's perfect, all I have to say is congratulations! Great job!

Thank you

Closing issue as it doesn't seem to have that problem.
