### ISSUE TITLE
Re adding to queue 

### ISSUE THREAD

**Issue by gadocum** [Meviii/LOL-Account-Checker#46]
![Adsız](https://user-images.githubusercontent.com/122527899/231406845-8bc796f5-b710-474d-9d5d-15c6ab9ade4e.jpg)

I keep getting this error. I tried thread count 1-8 all but still getting the same error. Can you help?

**Comment by Meviii** [comment]
Will look into this in a few days. Thanks for letting me know.

**Comment by Meviii** [comment]
Added notes regarding this in new release.
