### ISSUE TITLE
add option 

### ISSUE THREAD

**Issue by Dorlander** [Meviii/LOL-Account-Checker#52]
to dont check account friends it cost so much time (just add checkbox in Tasks)

**Comment by Meviii** [comment]
Is this for checking friend count or removing friends?

If its for checking the friend count, it is almost instant (for all the times I checked it).

If it is for removing friends, you can disable the task.

**Comment by Dorlander** [comment]
> Is this for checking friend count or removing friends?
> 
> If its for checking the friend count, it is almost instant (for all the times I checked it).
> 
> If it is for removing friends, you can disable the task.

count sure, i know but see at this 64 kb account with 200+ friends and every name start new line like this, just i want say, for economy space and more faster accounts loading in checker menu, add disable friends name check please 
![image](https://user-images.githubusercontent.com/61416392/235046034-a57d9245-3ec1-4822-85fc-d36cf5f28607.png)
![image](https://user-images.githubusercontent.com/61416392/235046149-5a451adc-2d96-48c2-8196-7225c5f0d68f.png)

**Comment by Meviii** [comment]
> > Is this for checking friend count or removing friends?
> > If its for checking the friend count, it is almost instant (for all the times I checked it).
> > If it is for removing friends, you can disable the task.
> 
> count sure, i know but see at this 64 kb account with 200+ friends and every name start new line like this, just i want say, for economy space and more faster accounts loading in checker menu, add disable friends name check please 

I understand what you mean, thanks for letting me know about that.
