### ISSUE TITLE
ERROR PATH

### ISSUE THREAD

**Issue by Thepablodurao** [Meviii/LOL-Account-Checker#53]
An error ocurred. Wrong cliente path.

path is ok

C:\Riot Games\Riot Client
C:\Riot Games\League of Legends

**Comment by Meviii** [comment]
Most likely it isn't okay. You cannot path to the folder so you need to path to the .exe file.

Please send me screenshots if your paths.

**Comment by Thepablodurao** [comment]
i try for league.exe
C:\Riot Games\League of Legends\LeagueClient.exe
and
C:\Riot Games\League of Legends\Game\League of Legends.exe

i try for riotclienteservices 

C:\Riot Games\Riot Client\RiotClientServices.exe

**Comment by Meviii** [comment]
could you send me your settings.json file found in DataFiles folder please.

**Comment by Thepablodurao** [comment]
{
  "RiotClientPath": "C:\\Riot Games\\Riot Client\\RiotClientServices.exe",
  "LeagueClientPath": "C:\\Riot Games\\League of Legends\\Game\\League of Legends.exe",
  "ComboListPath": "C:\\Users\\pablo.jonas\\Documents\\Novo Documento de Texto (1).txt"
}

**Comment by Meviii** [comment]
should be LeagueClient.exe, not League of Legends.exe

**Comment by Thepablodurao** [comment]
i try, same error.

C:\Riot Games\League of Legends\LeagueClient.exe

Initializing new Connection. Port: 61067, Auth Token: zsId2w8F7fhu7EZFbMok3r

**Comment by Thepablodurao** [comment]
{
  "RiotClientPath": "C:\\Riot Games\\Riot Client\\RiotClientServices.exe",
  "LeagueClientPath": "C:\\Riot Games\\League of Legends\\LeagueClient.exe",
  "ComboListPath": "C:\\Users\\pablo.jonas\\Documents\\Novo Documento de Texto (1).txt"
}
