### ISSUE TITLE
Some advice with respect

### ISSUE THREAD

**Issue by dd395674558** [Meviii/LOL-Account-Checker#54]
1.Could please allow the users use this software only to find out the right acc_pwd in files but do not launch the LOL client?
2.It seems like PPTP VPN can solve the rate_limited problem.I think sir you can change IP if rate is limited by using the VPN function in WIN7 or WIN10.
3.I can't check the account in Taiwan region,how to deal with it ?
Hope you can reply and send me emails because i have more thing to talk with you sir .

**Comment by Meviii** [comment]
> 1.Could please allow the users use this software only to find out the right acc_pwd in files but do not launch the LOL client? 
Sorry, I didn't quite understand this. Do you mean that accounts that should login aren't logging in due to wrong pass(or another reason)?

> 2.It seems like PPTP VPN can solve the rate_limited problem.I think sir you can change IP if rate is limited by using the VPN function in WIN7 or WIN10. 
Will look into this.

> 3.I can't check the account in Taiwan region, how to deal with it ? 
I don't think I can support for TW/CN servers as they have there own clients. But Ill still have a quick look into it as well.

> Hope you can reply and send me emails because I have more thing to talk with you sir .
You can let me know here what your suggestions/bugs are and Ill gladly take a look at them.

**Comment by dd395674558** [comment]
> > 1.Could please allow the users use this software only to find out the right acc_pwd in files but do not launch the LOL client?
> 
> Sorry, I didn't quite understand this. Do you mean that accounts that should login aren't logging in due to wrong pass(or another reason)?
> I mean , when one account successfully login the Riot Client , man can choose that if we launch the LOL Client.
In that way people will find out all the correct account_password combo very quickly in a large account_password combo txt file.
> > 2.It seems like PPTP VPN can solve the rate_limited problem.I think sir you can change IP if rate is limited by using the VPN function in WIN7 or WIN10.
> 
> Will look into this.
> 
> > 3.I can't check the account in Taiwan region, how to deal with it ?
> 
> I don't think I can support for TW/CN servers as they have there own clients. But Ill still have a quick look into it as well.
> The CNservers has its own client,but TW servers does not.
> > Hope you can reply and send me emails because I have more thing to talk with you sir .
> 
> You can let me know here what your suggestions/bugs are and Ill gladly take a look at them.
Of course sir.

**Comment by dd395674558** [comment]
> > > 1.Could please allow the users use this software only to find out the right acc_pwd in files but do not launch the LOL client?
> > 
> > 
> > Sorry, I didn't quite understand this. Do you mean that accounts that should login aren't logging in due to wrong pass(or another reason)?
> > I mean , when one account successfully login the Riot Client , man can choose that if we launch the LOL Client.
> > In that way people will find out all the correct account_password combo very quickly in a large account_password combo txt file.
> > > 2.It seems like PPTP VPN can solve the rate_limited problem.I think sir you can change IP if rate is limited by using the VPN function in WIN7 or WIN10.
> > 
> > 
> > Will look into this.
> > > 3.I can't check the account in Taiwan region, how to deal with it ?
> > 
> > 
> > I don't think I can support for TW/CN servers as they have there own clients. But Ill still have a quick look into it as well.
> > The CNservers has its own client,but TW servers does not.
> > > Hope you can reply and send me emails because I have more thing to talk with you sir .
> > 
> > 
> > You can let me know here what your suggestions/bugs are and Ill gladly take a look at them.
> > Of course sir.I just want to make a donation

**Comment by Meviii** [comment]
1. Do you mean only using the Riot Client to check login_pass? That is possible but I don't think Ill implement that anytime soon.
3. Seems like implementing the TW server might take some time. Ill implement it later on if it is even possible.

**Comment by dd395674558** [comment]
> 1. Do you mean only using the Riot Client to check login_pass? That is possible but I don't think Ill implement that anytime soon.
What a pity...But I still hope that you can change your mind,I can pay for it of course.
> 2. Seems like implementing the TW server might take some time. Ill implement it later on if it is even possible.
Thank you sir.

**Comment by Meviii** [comment]
Let me know on Discord if you would like a separate addon. Mevi#0001
