### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by ZaryImortal** [Meviii/LOL-Account-Checker#56]
Could add a way to stop the checker and continue from where it left off, this way it allows to put big combolist and close the program without having to wait the whole combolist.

**Comment by Meviii** [comment]
Yea, that seems like a good idea but not very easy to implement. I can temporarily add a most recent account checked status to know where the checker stopped. That way, you can start checking from the account that it was left at.

**Comment by ZaryImortal** [comment]
add some way to export everything in a .txt
example: SERVER:LOGIN:PASS:NAME:RP:BLUE ESSENCES:SKINS

Or a way to send to discord by webhook

**Comment by Meviii** [comment]
> add some way to export everything in a .txt example: SERVER:LOGIN:PASS:NAME:RP:BLUE ESSENCES:SKINS
> 
> Or a way to send to discord by webhook

Done this but in a fixed format.

> Could add a way to stop the checker and continue from where it left off, this way it allows to put big combolist and close the program without having to wait the whole combolist.

Will work on this when I get the chance
