### ISSUE TITLE
dont work for me

### ISSUE THREAD

**Issue by Shomedey** [Meviii/LOL-Account-Checker#59]
![image_2023-05-18_125317364](https://github.com/Meviii/LOL-Account-Checker/assets/31660343/03166738-45ef-4d5e-88b5-a267c5d08ae8)
![image_2023-05-18_130245381](https://github.com/Meviii/LOL-Account-Checker/assets/31660343/fe36ab29-190a-4715-bc7e-99dda272ec2f)

Hi, I'm trying to check accounts, I tried on a combo list it spams only that for hours + re-add queue and on a quick check it's the same then it tells me "task completed" without having done it

**Comment by ZaryImortal** [comment]
decrease tasks number and thread number

**Comment by Shomedey** [comment]
> decrease tasks number and thread number

Thanks for ur reply, don't work for me even with 1 thread and no task

![image_2023-05-20_183112725](https://github.com/Meviii/LOL-Account-Checker/assets/31660343/f29cbc5e-3444-4110-ab83-4f2b20f64740)
idk if that can help for something
