### ISSUE TITLE
Postman request

### ISSUE THREAD

**Issue by Aerowiel** [Meviii/LOL-Account-Checker#60]
Hello, i'm trying to make the same request as you but in Golang (I'm trying to make a prototype of it in Golang without an user interface)

To debug and understand how the rso connection works i'm trying to replicate your way of doing it in Postman but i'm getting this response on the "/rso-auth/v2/authorizations" 

```json
{
    "errorCode": "RPC_ERROR",
    "httpStatus": 400,
    "implementationDetails": {},
    "message": "A value for 'authorizationRequest' is required."
}
```

Do you know what it means ? I couldn't find anything about it. 
So far i know that : 
- My Basic auth is ok (i generated the auth token like you did and started the RiotClient with the same auth token)
- My body (type JSON) seems to be ok : 
```json
{
	"clientId":"riot-client",
	"trustLevels": "['always_trusted']"
}
```

Thanks in advance for your help :)

**Comment by Meviii** [comment]
1. Run Riot Client with specific Port and AuthToken and other required args
 
(can be found in RiotConnection.cs)
![image](https://github.com/Meviii/LOL-Account-Checker/assets/79978283/c5cffc3e-ce47-45f9-b2fb-f7b954c6e56c)

2. Post to /rso-auth/v2/authorizations with the data you wrote above as payload. Add it into a while loop just incase it fails(not 400 status code)

I cant see why It won't work unless you are using the wrong args for the client. Refer to this code(found in Runner.cs) for the steps to running the Riot Client:

![image](https://github.com/Meviii/LOL-Account-Checker/assets/79978283/829c6f3a-72a2-4a68-93f2-2fa8680becec)
