### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by YoussefFox** [Meviii/LOL-Account-Checker#62]
i get these errors knowing that i put the correct paths
![Screenshot 2023-05-21 123045](https://github.com/Meviii/LOL-Account-Checker/assets/134199450/d2927270-9ebc-4980-9fb4-1cb4d347f15c)
![Screenshot 2023-05-21 123112](https://github.com/Meviii/LOL-Account-Checker/assets/134199450/4083a7b3-4276-4ffc-b9a9-c1e1a6305dfd)
![Screenshot 2023-05-21 123143](https://github.com/Meviii/LOL-Account-Checker/assets/134199450/c8b92605-8cb6-4fee-aa1e-d5f2bfb87067)
[error.txt](https://github.com/Meviii/LOL-Account-Checker/files/11524165/error.txt)

**Comment by Meviii** [comment]
Still having this issue?
