### ISSUE TITLE
Looping "Sending GET request. URL: rnet-lifecycle/v1/product-context-phase" until failed

### ISSUE THREAD

**Issue by huankinder** [Meviii/LOL-Account-Checker#65]
Set paths, add list, hit start and on the first account I just get "Sending GET request. URL: rnet-lifecycle/v1/product-context-phase" forever without anything else happening. Full log:

> Initializing new Connection. Port: 50923, Auth Token: K0TQFRb2pCIFahtCXFF62Y
Sending POST request. URL: rso-auth/v2/authorizations
Response: OK
Sending PUT request. URL: rso-auth/v1/session/credentials
Response: Created
Sending PUT request. URL: eula/v1/agreement/acceptance
Response: Created
Sending GET request. URL: riotclient/region-locale
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK
Sending GET request. URL: rnet-lifecycle/v1/product-context-phase
Response: OK

**Comment by Meviii** [comment]
will look into this as soon as I can

**Comment by mrhammerthis** [comment]
I'm also suffering from this bug

**Comment by Meviii** [comment]
This problem is related to the RIOT API status for that specific endpoint. The checker works fine now...

For the future release, I will add an exception to catch that specific status to let you know to try later.
