### ISSUE TITLE
Looping at product-context-phase

### ISSUE THREAD

**Issue by 201912345** [Meviii/LOL-Account-Checker#69]
<img width="700" alt="32323233113" src="https://github.com/Meviii/LOL-Account-Checker/assets/136480882/34731fac-e47b-4108-ba64-aa29fe59d31a">
 
Was working fine for a while now it always gets stuck and loops at context-phase no clue the python version your version is based on does not do that and still works fine for me tryed 3 versions all do the same

**Comment by ADSFSAAFA** [comment]
Yes, I'm in the same situation

**Comment by Dramorian** [comment]
It takes too much time and makes it seem like it doesn't work. I was trying to check 30 accounts and after 10 minutes I got nothing, only a hundred re-queues.

**Comment by Meviii** [comment]
New update should fix this... Will look into it further once I find the time

**Comment by ADSFSAAFA** [comment]
> 新的更新应该可以解决此问题...一旦我找到时间，就会进一步研究它

Thank you author
